name: setup-tq
description: Setup GitHub Actions with tq (tomlq)
author: remarkablemark

inputs:
  version:
    description: Version
    required: false
    default: 0.2.2

runs:
  using: composite
  steps:
    # https://github.com/marketplace/actions/install-cargo-binstall
    - name: Install Binstall
      uses: cargo-bins/cargo-binstall@v1.17.4

    # https://github.com/cryptaliagy/tomlq
    - name: Install tq
      shell: bash
      run: cargo binstall -y tomlq@$VERSION
      env:
        VERSION: ${{ inputs.version }}

branding:
  icon: type
  color: white
